### ISSUE TITLE
Robonect integration

### ISSUE THREAD

**Issue by AndyS-112** [RonnyWinkler/homeassistant.homey#4]
Hallo, ich nutze deine App um meine HomeAssistant Geräte in Homey zu steuern. Funktioniert alles bestens! Ich bin begeistert. Ich nutze das ganze erst wenige Tage. Ich habe in HomeAssistant mein Robonect Modul für meinen Husqvarna Mähroboter hinzugefügt. Nun würde ich diesen ebenfalls gern über Homey steuern. Unterstützt wird derzeit aber nur die Integration eines Staubsaugroboters. Ist es möglich das ganze auch auf Robonect zu erweitern?
Viele Grüße 
Andreas

**Comment by RonnyWinkler** [comment]
Hallo Andreas,
dieses Repository betrifft nur die HA-Integration. Also die Möglichkeit, CompoundDevices in HA zu erstellen und diese als "Gruppe" an Homey zu synchronisieren.
Der passende Repository wäre: https://github.com/RonnyWinkler/io.home-assistant.community
Ode einfach im Forum fragen :-)
https://community.homey.app/t/app-pro-home-assistant-community-app-deutsch/71478
oder https://community.homey.app/t/app-pro-home-assistant-community-app/71477

Ich schließe daher diesen Issue. Wir können deine Frage aber ganz unabhängig davon klären. Ich denke, es braucht keine Integration für deinen Roboter. Das HA-Gerät wird nur eine Gruppierung diverser Entitäten sein.
Die Homey-Geräte (Staubsauger) sind jeweils für eine HA-Domain (vaccum) definiert. 
Ich nehme an, dein Roboter besitzt nur Schalter (switch) und Sensoren (sensor, binary_sensor) Entitäten. Die kann man in Homey auf verschiedene Weise importieren und zu einem Gerät zusammenfassen. Das geht z.B. über eine Schalter-Entität des Roboters und Hinzufügen der Sensoren (Geräte-Einstellungen).

Bitte stelle deine Frage nochmal im deutschen Thread (erster Forum link oben) und poste dazu Screenshots von deinem HA-Gerät (Einstellungen/Geräte, dein Gerät).
![grafik](https://github.com/RonnyWinkler/homeassistant.homey/assets/49495550/1d0a2887-8615-4425-9a7b-f9a417a6e777)
Dann können wir das Schritt für Schritt durchgehen. Danke.

Viele Grüße
Ronny
